version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: filmoteka-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./filmoteka-postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 7s
      timeout: 7s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all" ]
  filmoteka:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MIGRATIONS: ${MIGRATIONS}
      SERVICE_HOST: ${SERVICE_HOST}
      JWT_KEY: ${JWT_KEY}
    volumes:
      - ./${MIGRATIONS}:/filmoteka/${MIGRATIONS}
      - ./${LOG_FILE_PATH}:/filmoteka/${LOG_FILE_PATH}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"